/**
 * Reads database/catalog-seed.tsv and writes:
 *   - database/seed_training_catalog.sql
 *   - assets/js/courses_catalog.js (stable IDs for visitor fallback)
 * TSV format: path_index (0-16) | title | content_type (course|diploma)
 */
import fs from "fs";
import path from "path";
import crypto from "crypto";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const PATH_IDS = [
    "6f218ea3-2986-480f-bd9c-e363b114ebea",
    "793b500b-b6c7-434d-8f22-4c6edaa99ef7",
    "f75ebf5c-1149-403b-adc8-d71998a66677",
    "88b45ee8-0d68-4b6f-950f-31fafe090f2c",
    "2382a403-f79e-4e3b-95c2-369c38c8b892",
    "d34ecdf9-1491-4994-8412-c63a604e8071",
    "fc905b85-c454-4308-b18c-4e883e618a19",
    "86ca55a6-f9c1-4c5e-8017-72d0277f511c",
    "5f32c274-58df-4cbb-b05b-c5ec433fc995",
    "fc275b08-665b-43e4-a6f4-d4796c399741",
    "0284e552-2561-4d4e-95c6-9ea07a4c09f0",
    "d218da2f-8920-43f1-ad5e-325b86894fa5",
    "7e8f979b-9dba-4338-bbf7-7c5062d68f81",
    "13e3dad6-9f4f-4c65-b2d0-7395d68a9c83",
    "dc2f6f22-f742-42a2-af8b-d4d144497821",
    "deef2bec-3286-45a9-a183-7f3ba56d656c",
    "c9331f25-600f-4e8e-a51b-035b8678b2f4"
];

const PATH_META = [
    { slug: "al-qiyada-al-ulya", icon: "🎯", name: "مسار القيادة العليا" },
    { slug: "al-idara-al-wusta", icon: "📊", name: "مسار الإدارة الوسطى" },
    { slug: "al-iilam-wal-ittisal", icon: "📣", name: "مسار الإعلام والاتصال المؤسسي" },
    { slug: "taknikat-al-maalumat", icon: "💻", name: "مسار تقنية المعلومات" },
    { slug: "al-shuun-al-maliya", icon: "💰", name: "مسار الشؤون المالية" },
    { slug: "al-mawared-al-bashariya", icon: "👥", name: "مسار الموارد البشرية" },
    { slug: "al-baramij-al-taheeliya", icon: "🎓", name: "مسار البرامج التأهيلية" },
    { slug: "al-aghdiya", icon: "🍽️", name: "مسار الأغذية وسلامتها" },
    { slug: "al-riyada", icon: "⚽", name: "مسار الرياضة" },
    { slug: "al-masar-al-qanuni", icon: "⚖️", name: "المسار القانوني" },
    { slug: "al-masar-al-tatawiri", icon: "🌱", name: "المسار التطويري" },
    { slug: "al-masar-al-talimi", icon: "📖", name: "المسار التعليمي" },
    { slug: "al-amn-wal-salama", icon: "🛡️", name: "مسار الأمن والسلامة" },
    { slug: "al-idara-al-sihiya", icon: "🏥", name: "مسار الإدارة الصحية" },
    { slug: "al-fanni-wal-handasi", icon: "🏗️", name: "المسار الفني والهندسي" },
    { slug: "al-fundiqa-wal-siyaha", icon: "🏨", name: "مسار الفندقة والسياحة" },
    { slug: "al-diblumat", icon: "🎖️", name: "مسار الدبلومات التخصصية" }
];

function escSql(s) {
    return String(s || "").replace(/'/g, "''");
}

function escJs(s) {
    return JSON.stringify(String(s || ""));
}

/** Deterministic UUID from path + title (matches seed + courses_catalog.js). */
function courseId(pathId, title) {
    const hash = crypto.createHash("sha1").update("maher-course:" + pathId + ":" + title, "utf8").digest();
    hash[6] = (hash[6] & 0x0f) | 0x50;
    hash[8] = (hash[8] & 0x3f) | 0x80;
    const hex = hash.toString("hex").slice(0, 32);
    return (
        hex.slice(0, 8) +
        "-" +
        hex.slice(8, 12) +
        "-" +
        hex.slice(12, 16) +
        "-" +
        hex.slice(16, 20) +
        "-" +
        hex.slice(20, 32)
    );
}

const tsvPath = path.join(__dirname, "catalog-seed.tsv");
const raw = fs.readFileSync(tsvPath, "utf8");
const lines = raw.split(/\r?\n/).filter(function (l) {
    return l.trim() && !l.trim().startsWith("#");
});

const courseRows = [];

lines.forEach(function (line) {
    const parts = line.split("\t");
    if (parts.length < 2) return;
    const idx = parseInt(parts[0], 10);
    const title = parts[1].trim();
    let ctype = (parts[2] || "course").trim().toLowerCase();
    if (ctype !== "diploma") ctype = "course";
    if (isNaN(idx) || idx < 0 || idx >= PATH_IDS.length) return;
    const pid = PATH_IDS[idx];
    const cat = PATH_META[idx].name;
    courseRows.push({
        id: courseId(pid, title),
        title,
        category: cat,
        training_path_id: pid,
        content_type: ctype,
        price_type: "free",
        price_amount: 0,
        max_seats: 0,
        is_active: true
    });
});

let out = "";
out += "-- Generated by database/generate_training_seed.mjs — run AFTER training_paths_migration.sql\n";
out += "BEGIN;\n";

PATH_META.forEach(function (meta, i) {
    const id = PATH_IDS[i];
    out +=
        "INSERT INTO public.training_paths (id, slug, name_ar, icon, sort_order, is_active) VALUES (" +
        "'" +
        id +
        "', '" +
        escSql(meta.slug) +
        "', '" +
        escSql(meta.name) +
        "', '" +
        escSql(meta.icon) +
        "', " +
        (i + 1) +
        ", true) ON CONFLICT (id) DO UPDATE SET name_ar = EXCLUDED.name_ar, icon = EXCLUDED.icon, sort_order = EXCLUDED.sort_order;\n";
});

courseRows.forEach(function (row) {
    out +=
        "INSERT INTO public.courses (id, title, description, category, training_path_id, content_type, price_type, price_amount, max_seats, is_active) VALUES (" +
        "'" +
        row.id +
        "', '" +
        escSql(row.title) +
        "', NULL, '" +
        escSql(row.category) +
        "', '" +
        row.training_path_id +
        "', '" +
        row.content_type +
        "', 'free', 0, 0, true) ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, category = EXCLUDED.category, training_path_id = EXCLUDED.training_path_id, content_type = EXCLUDED.content_type, is_active = EXCLUDED.is_active;\n";
});

out += "COMMIT;\n";
fs.writeFileSync(path.join(__dirname, "seed_training_catalog.sql"), out, "utf8");

let js =
    "/**\n * الكتالوج الافتراضي للدورات — نفس معرّفات seed_training_catalog.sql\n * عرض للزوار إن كان جدول courses فارغاً أو القراءة محجوبة.\n */\n(function () {\n    \"use strict\";\n    window.maherDefaultCourses = [\n";

courseRows.forEach(function (row, i) {
    js +=
        "        { id: " +
        escJs(row.id) +
        ", title: " +
        escJs(row.title) +
        ", description: null, category: " +
        escJs(row.category) +
        ", training_path_id: " +
        escJs(row.training_path_id) +
        ", content_type: " +
        escJs(row.content_type) +
        ", price_type: " +
        escJs(row.price_type) +
        ", price_amount: 0, max_seats: 0, is_active: true }" +
        (i < courseRows.length - 1 ? "," : "") +
        "\n";
});

js += "    ];\n})();\n";

const jsPath = path.join(__dirname, "..", "assets", "js", "courses_catalog.js");
fs.writeFileSync(jsPath, js, "utf8");

console.log("Wrote seed_training_catalog.sql (" + courseRows.length + " course rows)");
console.log("Wrote assets/js/courses_catalog.js");
